#include <stdlib.h>
#include <string.h>
#include <libxml/parser.h>
#include <stdio.h>

#include <bsgen_string.h>
#include <bsgen_list.h>

#define BSGEN_MIN(a,b) (((a)<(b))?(a):(b))
#define BSGEN_MAX(a,b) (((a)>(b))?(a):(b))

#define BSGEN_NEWLINE "\r\n"
#define BSGEN_STRING_LEN(s) (sizeof(s) - 1)

#define BSGEN_GENERATE_COMMENT \
    " /**" BSGEN_NEWLINE \
    "  This file was generated by basilisk-gen." BSGEN_NEWLINE BSGEN_NEWLINE \
    "  It is not recommended to make changes to this file as it will be lost if" BSGEN_NEWLINE \
    "  the code is regenerated." BSGEN_NEWLINE \
    " */"

 /** Includes */
typedef struct {
    char* file;
} bsgen_Include;

 /** Typedefs */
typedef struct {
    char* type;
    char* name;
} bsgen_Typedef;

 /** Enums */
typedef struct {
    char* name;
    char* value;
} bsgen_EnumValue;

typedef struct {
    char* name;
    bsgen_List values;
} bsgen_Enum;

 /** Macros */
typedef struct {
    char* value;
} bsgen_MacroLine;

typedef struct {
    char* name;
    bsgen_List lines;
} bsgen_Macro;

 /** Structs */
typedef struct {
    char* name;
    char* type;
} bsgen_Field;

typedef struct {
    char* name;
    bsgen_List fields;
    int is_union;
} bsgen_Structure;

 /** Functions */
typedef struct {
    char* name;
    char* type;
    char* comment;
} bsgen_Param;

typedef struct {
    char variadic;
    char* string_format;
    char* name;
    char* return_value;
    bsgen_List params;

    int generated_from_function_id;
} bsgen_Function;

 /** Externs */
typedef struct {
    char* type;
    char* name;
} bsgen_Extern;

typedef struct {
    const char* path;
    bsgen_List includes;
    bsgen_List typedefs;
    bsgen_List enums;
    bsgen_List macros;
    bsgen_List structures;
    bsgen_List functions;
    bsgen_List externs;
} bsgen_Library;

void bsgen_warning(const char* format, ...) {
    va_list args;
    va_start(args, format);
    vprintf(format, args);
    va_end(args);
}

static bsgen_String* bsgen_loadFileFromHandle(FILE* file) {
    fseek(file, 0, SEEK_END);
    long len = ftell(file) + 1;
    fseek(file, 0, SEEK_SET);

    bsgen_String* string = bsgen_stringAlloc(NULL, len);
    string->len = len;

    fread(string->value, 1, len, file);
    fclose(file);

    string->value[len - 1] = '\0';
    return string;
}

bsgen_String* bsgen_loadFile(const char* path) {
    FILE* file = fopen(path, "rb");
    if (!file) {
        bsgen_warning("Failed to load file \"%s\"\n", path);
        exit(1);
        return NULL;
    }
    return bsgen_loadFileFromHandle(file);
}

void bsgen_saveFile(const char* path, char* data, unsigned int data_len) {
    FILE* file = fopen(path, "wb");
    if (!file) {
        bsgen_warning("Failed to save file \"%s\"\n", path);
        return;
    }

    if (data)
        fwrite(data, data_len, 1, file);
    fclose(file);
}

void bsgen_saveFileF(char* data, unsigned int data_len, char* format, ...) {
    static bsgen_String* string;

    va_list args;
    va_start(args, format);
    string = bsgen_stringV(string, format, args);
    va_end(args);

    bsgen_saveFile(string->value, data, data_len);
}



  /*==============================================================================
   * XML Reader
   *============================================================================*/

static xmlChar* bsgen_getProperty(xmlNode* node, const char* name) {
    xmlAttr* property = node->properties;
    while (property) {
        if (xmlStrcmp(property->name, name) == 0)
            return property->children->content;

        property = property->next;
    }

    return NULL;
}

static xmlNode* bsgen_getSingleChild(xmlNode* node, const char* name) {
    xmlNode* child = node->children;
    xmlNode* result = NULL;

    while (child) {
        if (xmlStrcmp(child->name, name) == 0) {
            if (result) {
                bsgen_warning("Node \"%s\" has more than one child with name \"%s\"\n", node->name, name);
                return NULL;
            }
            result = child;
        }

        child = child->next;
    }

    return result;
}

 /**
  Include
  */
static void bsgen_readInclude(xmlNode* node, bsgen_Include* out) {
    out->file = xmlStrdup(node->children->content);
}

 /**
  Typedef
  */
static void bsgen_readTypedef(xmlNode* node, bsgen_Typedef* out) {
    xmlNode* type_node = bsgen_getSingleChild(node, "type");
    xmlNode* name_node = bsgen_getSingleChild(node, "name");

    if (!type_node || !name_node)
        return (bsgen_Field) { 0 };

    out->name = xmlStrdup(name_node->children->content);
    out->type = xmlStrdup(type_node->children->content);
}

 /**
  Enum
  */
static bsgen_EnumValue bsgen_readEnumValue(xmlNode* node) {
    xmlNode* child = node->children;

    xmlNode* value_node = bsgen_getSingleChild(node, "value");
    xmlNode* name_node = bsgen_getSingleChild(node, "name");

    if (!name_node) {
        bsgen_warning("Name is a required property of \"%s\"\n", node->name);
        return (bsgen_EnumValue) { 0 };
    }

    bsgen_EnumValue value = {
        .name = xmlStrdup(name_node->children->content),
        .value = value_node ? xmlStrdup(value_node->children->content) : NULL,
    };

    return value;
}

static void bsgen_readEnum(xmlNode* node, bsgen_Enum* out) {
    char* name = bsgen_getProperty(node, "name");

    if (!name)
        return bsgen_warning("Name is a required property of \"%s\"\n", node->name);
    
    out->name = name;
    out->values = BSGEN_LIST(bsgen_EnumValue);
    
    xmlNode* child = node->children;
    while (child) {
        if (child->type == XML_ELEMENT_NODE) {
            if (xmlStrcmp(child->name, "line") == 0) {
                bsgen_EnumValue value = bsgen_readEnumValue(child);

                bsgen_pushBack(&out->values, &value);
            }
        }

        child = child->next;
    }
}

 /**
  Macro
  */
static void bsgen_readMacro(xmlNode* node, bsgen_Macro* out) {
    xmlNode* name_node = bsgen_getSingleChild(node, "name");

    if (!name_node)
        return bsgen_warning("Name is a required property of \"%s\"\n", node->name);

    out->name = xmlStrdup(name_node->children->content);
    out->lines = BSGEN_LIST(bsgen_MacroLine);

    xmlNode* child = node->children;
    while (child) {
        if (child->type == XML_ELEMENT_NODE) {
            if (xmlStrcmp(child->name, "line") == 0) {
                bsgen_MacroLine line = {
                    .value = xmlStrdup(child->children->content),
                };

                bsgen_pushBack(&out->lines, &line);
            }
        }

        child = child->next;
    }
}

 /**
  Structure
  */
static bsgen_Field bsgen_readField(xmlNode* node) {
    xmlNode* child = node->children;

    xmlNode* type_node = bsgen_getSingleChild(node, "type");
    xmlNode* name_node = bsgen_getSingleChild(node, "name");

    if (!type_node || !name_node)
        return (bsgen_Field) { 0 };

    bsgen_Field field = {
        .name = xmlStrdup(name_node->children->content),
        .type = xmlStrdup(type_node->children->content),
    };

    return field;
}

static void bsgen_readStructure(xmlNode* node, bsgen_Structure* out) {
    char* structure_name = bsgen_getProperty(node, "name");
    char* structure_type = bsgen_getProperty(node, "type");

    if (!structure_name)
        return;

    xmlNode* child = node->children;

    out->name = xmlStrdup(structure_name);
    out->is_union = structure_type && xmlStrcmp(structure_type, "union") == 0;
    out->fields = BSGEN_LIST(bsgen_Field);

    while (child) {
        if (child->type == XML_ELEMENT_NODE) {
            if (xmlStrcmp(child->name, "field") == 0) {
                bsgen_Field field = bsgen_readField(child);
                bsgen_pushBack(&out->fields, &field);
            }
        }

        child = child->next;
    }
}

 /**
  Functions
  */
static bsgen_Param bsgen_readParam(xmlNode* node) {
    xmlNode* child = node->children;

    xmlNode* type_node = bsgen_getSingleChild(node, "type");
    xmlNode* name_node = bsgen_getSingleChild(node, "name");

    if (!name_node)
        return (bsgen_Param) { 0 };

    bsgen_Param param = {
        .name = xmlStrdup(name_node->children->content),
        .type = type_node ? xmlStrdup(type_node->children->content) : NULL,
        .comment = bsgen_getProperty(node, "comment"),
    };

    return param;
}

static void bsgen_readFunction(xmlNode* node, int original_function_id, bsgen_Function* out, char variadic) {
    static bsgen_String* string;

    xmlChar* function_name = bsgen_getProperty(node, "name");

    if (!function_name)
        return;

    xmlNode* child = node->children;
    xmlNode* return_value = bsgen_getSingleChild(node, "return");
    if (!return_value)
        return;

    xmlChar* string_format = bsgen_getProperty(node, "stringFormat");
    if (string_format) {
        out->name = strdup((string = bsgen_stringF(string, "%s%c", function_name, variadic))->value);
        out->string_format = xmlStrdup(string_format);
    }
    else
        out->name = xmlStrdup(function_name);

    out->return_value = xmlStrdup(return_value->children->content);
    out->params = BSGEN_LIST(bsgen_Param);
    out->variadic = variadic;
    out->generated_from_function_id = original_function_id;

    while (child) {
        if (child->type == XML_ELEMENT_NODE) {
            if (xmlStrcmp(child->name, "param") == 0) {
                bsgen_Param param = bsgen_readParam(child);
                bsgen_pushBack(&out->params, &param);
            }
        }

        child = child->next;
    }

    switch (variadic) {
    case 'N':
        bsgen_pushBack(&out->params, &(bsgen_Param) {
            .name = strdup((string = bsgen_stringF(string, "%s_length", out->string_format))->value),
            .type = "int",
        });
        break;
    case 'V':
        bsgen_pushBack(&out->params, &(bsgen_Param) {
            .name = "args",
            .type = "va_list",
        });
        break;
    case 'F':
        bsgen_pushBack(&out->params, &(bsgen_Param) {.name = "..." });
        break;
    }
}

 /**
  Externs
  */
static void bsgen_readExtern(xmlNode* node, bsgen_Extern* out) {
    xmlNode* type = bsgen_getSingleChild(node, "type");
    xmlNode* name = bsgen_getSingleChild(node, "name");

    if (!type || !name)
        return bsgen_warning("Type and name are required properties of \"%s\"\n", node->name);

    out->type = xmlStrdup(type->children->content);
    out->name = xmlStrdup(name->children->content);
}

 /**
  Library
  */
static void bsgen_readGeneric(bsgen_List* list, xmlNode* node, const char* type, void(*callback)(xmlNode* node, void* data)) {
    xmlNode* child = node->children;

    while (child) {
        if (child->type == XML_ELEMENT_NODE) {
            if (xmlStrcmp(child->name, type) == 0) {
                void* data = bsgen_pushBack(list, NULL);
                callback(child, data);
            }
        }

        child = child->next;
    }
}

static void bsgen_readFunctions(bsgen_List* list, xmlNode* node, const char* type) {
    xmlNode* child = node->children;

    while (child) {
        if (child->type == XML_ELEMENT_NODE) {
            if (xmlStrcmp(child->name, type) == 0) {
                bsgen_Function function = { 0 };
                bsgen_readFunction(child, -1, &function, 0);
                if (function.string_format) {
                    int original = list->count + 3;
                    bsgen_readFunction(child, original, bsgen_pushBack(list, NULL), 'N');
                    bsgen_readFunction(child, original, bsgen_pushBack(list, NULL), 'V');
                    bsgen_readFunction(child, original, bsgen_pushBack(list, NULL), 'F');
                    function.variadic = 1;
                }
                bsgen_pushBack(list, &function);
            }
        }

        child = child->next;
    }
}

static bsgen_Library bsgen_readLibrary(const char* path) {
    bsgen_Library library = {
        .path = path,
        .includes = BSGEN_LIST(bsgen_Include),
        .typedefs = BSGEN_LIST(bsgen_Typedef),
        .enums = BSGEN_LIST(bsgen_Enum),
        .macros = BSGEN_LIST(bsgen_Macro),
        .functions = BSGEN_LIST(bsgen_Function),
        .structures = BSGEN_LIST(bsgen_Structure),
        .externs = BSGEN_LIST(bsgen_Extern),
    };

    xmlDoc* document = xmlReadFile(path, NULL, 0);
    xmlNode* node = xmlDocGetRootElement(document)->children;

    while (node) {
        if (xmlStrcmp(node->name, "includes") == 0)
            bsgen_readGeneric(&library.includes, node, "include", bsgen_readInclude);
        else if (xmlStrcmp(node->name, "typedefs") == 0)
            bsgen_readGeneric(&library.typedefs, node, "typedef", bsgen_readTypedef);
        else if (xmlStrcmp(node->name, "enums") == 0)
            bsgen_readGeneric(&library.enums, node, "enum", bsgen_readEnum);
        else if (xmlStrcmp(node->name, "macros") == 0)
            bsgen_readGeneric(&library.macros, node, "macro", bsgen_readMacro);
        else if (xmlStrcmp(node->name, "structures") == 0)
            bsgen_readGeneric(&library.structures, node, "structure", bsgen_readStructure);
        else if (xmlStrcmp(node->name, "functions") == 0)
            bsgen_readFunctions(&library.functions, node, "function");
        else if (xmlStrcmp(node->name, "externs") == 0)
            bsgen_readGeneric(&library.externs, node, "extern", bsgen_readExtern);

        node = node->next;
    }

    return library;
}

static bsgen_String* bsgen_appendLicense(bsgen_String* string, bsgen_String* license) {
    string = bsgen_appendStringF(string, BSGEN_NEWLINE " /**" BSGEN_NEWLINE "%s" BSGEN_NEWLINE " */ " BSGEN_NEWLINE BSGEN_NEWLINE, license->value);
    string = bsgen_appendString(string, BSGEN_GENERATE_COMMENT BSGEN_NEWLINE BSGEN_NEWLINE, BSGEN_STRING_LEN(BSGEN_GENERATE_COMMENT BSGEN_NEWLINE BSGEN_NEWLINE));
    return string;
}

static bsgen_String* bsgen_appendHeaderDefines(bsgen_String* string, const char* header_id) {
    string = bsgen_appendStringF(string, "#ifndef %s" BSGEN_NEWLINE "#define % s" BSGEN_NEWLINE BSGEN_NEWLINE, header_id, header_id);
    return string;
}



 /*==============================================================================
  * Header Generation
  *============================================================================*/

static bsgen_String* bsgen_generateHeader(bsgen_String* string, bsgen_Library* library, const char* name, const char* header_id, const char* api_prefix) {
    string = bsgen_appendHeaderDefines(string, header_id);

   /**
    Includes
    */
    for (int i = 0; i < library->includes.count; i++) {
        bsgen_Include* include = bsgen_fetchUnit(&library->includes, i);
        string = bsgen_appendStringF(string, "#include <%s>" BSGEN_NEWLINE, include->file);
    }

    string = bsgen_appendString(string, BSGEN_NEWLINE, BSGEN_STRING_LEN(BSGEN_NEWLINE));

   /**
    Typedefs
    */
    for (int i = 0; i < library->typedefs.count; i++) {
        bsgen_Typedef* _typedef = bsgen_fetchUnit(&library->typedefs, i);
        string = bsgen_appendStringF(string, "typedef %s %s;" BSGEN_NEWLINE, _typedef->type, _typedef->name);
    }

    string = bsgen_appendString(string, BSGEN_NEWLINE, BSGEN_STRING_LEN(BSGEN_NEWLINE));

   /**
    Definitions
    */
    for (int i = 0; i < library->structures.count; i++) {
        bsgen_Structure* structure = bsgen_fetchUnit(&library->structures, i);
        string = bsgen_appendStringF(string, "typedef %s %s %s;" BSGEN_NEWLINE, (structure->is_union ? "union" : "struct"), structure->name, structure->name);
    }

    string = bsgen_appendString(string, BSGEN_NEWLINE, BSGEN_STRING_LEN(BSGEN_NEWLINE));

    for (int i = 0; i < library->enums.count; i++) {
        bsgen_Enum* _enum = bsgen_fetchUnit(&library->enums, i);
        string = bsgen_appendStringF(string, "typedef enum %s %s;" BSGEN_NEWLINE, _enum->name, _enum->name);
    }

    string = bsgen_appendString(string, BSGEN_NEWLINE, BSGEN_STRING_LEN(BSGEN_NEWLINE));


   /**
    Macros
    */
    for (int i = 0; i < library->macros.count; i++) {
        bsgen_Macro* macro = bsgen_fetchUnit(&library->macros, i);

        if (macro->lines.count > 0)
            string = bsgen_appendStringF(string, "%s \\" BSGEN_NEWLINE, macro->name);
        else
            string = bsgen_appendStringF(string, "%s" BSGEN_NEWLINE, macro->name);

        for (int j = 0; j < macro->lines.count; j++) {
            bsgen_MacroLine* line = bsgen_fetchUnit(&macro->lines, j);

            if (j == (macro->lines.count - 1))
                string = bsgen_appendStringF(string, "    %s" BSGEN_NEWLINE, line->value);
            else
                string = bsgen_appendStringF(string, "    %s \\" BSGEN_NEWLINE, line->value);
        }

        string = bsgen_appendString(string, BSGEN_NEWLINE, BSGEN_STRING_LEN(BSGEN_NEWLINE));
    }

    string = bsgen_appendString(string, BSGEN_NEWLINE, BSGEN_STRING_LEN(BSGEN_NEWLINE));

    /**
     Declarations
     */
    for (int i = 0; i < library->structures.count; i++) {
        bsgen_Structure* structure = bsgen_fetchUnit(&library->structures, i);
        string = bsgen_appendStringF(string, "%s %s {" BSGEN_NEWLINE, (structure->is_union ? "union" : "struct"), structure->name);
        
        for (int j = 0; j < structure->fields.count; j++) {
            bsgen_Field* field = bsgen_fetchUnit(&structure->fields, j);
            string = bsgen_appendStringF(string, "    %s %s;" BSGEN_NEWLINE, field->type, field->name);
        }

#define BSGEN_STRUCT_END "};" BSGEN_NEWLINE BSGEN_NEWLINE
        string = bsgen_appendString(string, BSGEN_STRUCT_END, BSGEN_STRING_LEN(BSGEN_STRUCT_END));
    }

    for (int i = 0; i < library->enums.count; i++) {
        bsgen_Enum* _enum = bsgen_fetchUnit(&library->enums, i);

        string = bsgen_appendStringF(string, "enum %s {" BSGEN_NEWLINE, _enum->name);

        for (int j = 0; j < _enum->values.count; j++) {
            bsgen_EnumValue* value = bsgen_fetchUnit(&_enum->values, j);
            if (value->value)
                string = bsgen_appendStringF(string, "    %s = %s," BSGEN_NEWLINE, value->name, value->value);
            else
                string = bsgen_appendStringF(string, "    %s," BSGEN_NEWLINE, value->name);
        }

#define BSGEN_STRUCT_END "};" BSGEN_NEWLINE BSGEN_NEWLINE
        string = bsgen_appendString(string, BSGEN_STRUCT_END, BSGEN_STRING_LEN(BSGEN_STRUCT_END));
    }

   /**
    Functions
    */
    for (int i = 0; i < library->functions.count; i++) {
        bsgen_Function* function = bsgen_fetchUnit(&library->functions, i);

         /**
          Comment
          */
        string = bsgen_appendStringF(string, " /**" BSGEN_NEWLINE);
        for (int j = 0; j < function->params.count; j++) {
            bsgen_Param* param = bsgen_fetchUnit(&function->params, j);
            string = bsgen_appendStringF(string, "  @param %s", param->type, param->name);
            if (param->comment)
                string = bsgen_appendStringF(string, " - %s", param->comment);
            string = bsgen_appendString(string, BSGEN_NEWLINE, BSGEN_STRING_LEN(BSGEN_NEWLINE));
        }
        string = bsgen_appendStringF(string, "  @return %s" BSGEN_NEWLINE "  */" BSGEN_NEWLINE, function->return_value);

        string = bsgen_appendStringF(string, "%s %s" BSGEN_NEWLINE "%s(", api_prefix, function->return_value, function->name);

        for (int j = 0; j < function->params.count; j++) {
            bsgen_Param* param = bsgen_fetchUnit(&function->params, j);
            if (param->type)
                string = bsgen_appendStringF(string, BSGEN_NEWLINE "    %s %s", param->type, param->name);
            else
                string = bsgen_appendStringF(string, BSGEN_NEWLINE "    %s", param->name);
            if (j != (function->params.count - 1))
                string = bsgen_appendString(string, ",", 1);
        }

#define BSGEN_FUNCTION_END ");" BSGEN_NEWLINE BSGEN_NEWLINE
        string = bsgen_appendString(string, BSGEN_FUNCTION_END, BSGEN_STRING_LEN(BSGEN_FUNCTION_END));
    }

   /**
    Externs
    */
    for (int i = 0; i < library->externs.count; i++) {
        bsgen_Extern* ext = bsgen_fetchUnit(&library->externs, i);
        string = bsgen_appendStringF(string, "%s extern %s _%s;" BSGEN_NEWLINE, api_prefix, ext->type, ext->name);
    }

    string = bsgen_appendStringF(string, BSGEN_NEWLINE "#endif");

    bsgen_saveFile(name, string->value, string->len);

    return string;
}



  /*==============================================================================
   * Trampoline Generation
   *============================================================================*/

#define BSGEN_END_OF_PARAMETERS ")" BSGEN_NEWLINE "{" BSGEN_NEWLINE
#define BSGEN_END_OF_FUNCTION "}" BSGEN_NEWLINE BSGEN_NEWLINE

static bsgen_String* bsgen_generateTrampolineFunctionParameter(bsgen_String* string, bsgen_Param* param) {
    if (param->type)
        string = bsgen_appendStringF(string, BSGEN_NEWLINE "    %s %s", param->type, param->name);
    else
        string = bsgen_appendStringF(string, BSGEN_NEWLINE "    %s", param->name);

    return string;
}

static bsgen_String* bsgen_generateTrampolineFunctionParameters(bsgen_String* string, bsgen_Function* function) {
    for (int i = 0; i < function->params.count; i++) {
        bsgen_Param* param = bsgen_fetchUnit(&function->params, i);

        string = bsgen_generateTrampolineFunctionParameter(string, param);
        if (i != (function->params.count - 1))
            string = bsgen_appendString(string, ", ", BSGEN_STRING_LEN(", "));
    }

    return string;
}

static bsgen_String* bsgen_generateTrampolineFunctionBody(bsgen_String* string, bsgen_Function* function, const char* table_name) {
    string = bsgen_appendStringF(string, "    return %s.%s(", table_name, function->name);

    for (int i = 0; i < function->params.count; i++) {
        bsgen_Param* param = bsgen_fetchUnit(&function->params, i);
        string = bsgen_appendString(string, param->name, strlen(param->name));

        if (i != (function->params.count - 1))
            string = bsgen_appendString(string, ", ", BSGEN_STRING_LEN(", "));
    }

    string = bsgen_appendString(string, ");" BSGEN_NEWLINE, BSGEN_STRING_LEN(");" BSGEN_NEWLINE));

    return string;
}

static bsgen_String* bsgen_generateOriginalVariadicTrampolineFunction(bsgen_Library* library, bsgen_String* string, bsgen_Function* function, const char* table_name) {
    string = bsgen_appendStringF(string, "    return %sN(", function->name);

    for (int i = 0; i < function->params.count; i++) {
        bsgen_Param* param = bsgen_fetchUnit(&function->params, i);
        string = bsgen_appendStringF(string, "%s, ", param->name);
    }

    string = bsgen_appendStringF(string, "strlen(%s));" BSGEN_NEWLINE, function->string_format);

    return string;
}

static bsgen_String* bsgen_generateVariadicFormatTrampolineFunction(bsgen_Library* library, bsgen_String* string, bsgen_Function* function) {
    bsgen_Function* original = bsgen_fetchUnit(&library->functions, function->generated_from_function_id);
    string = bsgen_appendStringF(string,
        "    static bs_String* string;" BSGEN_NEWLINE
        "    string = bs_stringV(string, %s, args);" BSGEN_NEWLINE
        "    return %sN(",
        function->string_format,
        original->name
    );

    for (int i = 0; i < function->params.count; i++) {
        bsgen_Param* param = bsgen_fetchUnit(&function->params, i);
        if (strcmp(param->name, function->string_format) == 0)
            break;
        string = bsgen_appendStringF(string, "%s, ", param->name);
    }

#define BSGEN_END_OF_VARIADIC_FUNCTION "string->value, string->len);" BSGEN_NEWLINE BSGEN_END_OF_FUNCTION
     string = bsgen_appendString(string, "string->value, string->len);" BSGEN_NEWLINE, BSGEN_STRING_LEN("string->value, string->len);" BSGEN_NEWLINE));

    return string;
}

static bsgen_String* bsgen_generateFormatTrampolineFunction(bsgen_Library* library, bsgen_String* string, bsgen_Function* function) {
    bsgen_Function* original = bsgen_fetchUnit(&library->functions, function->generated_from_function_id);
    string = bsgen_appendStringF(string,
        "    va_list args;" BSGEN_NEWLINE
        "    va_start(args, %s);" BSGEN_NEWLINE
        "    %s _return = %sV(",
        original->string_format,
        function->return_value,
        original->name
    );

    for (int i = 0; i < function->params.count; i++) {
        bsgen_Param* param = bsgen_fetchUnit(&function->params, i);
        if (strcmp(param->name, function->string_format) == 0)
            break;
        string = bsgen_appendStringF(string, "%s, ", param->name);
    }

    string = bsgen_appendStringF(string,
        "%s, args"
        ");" BSGEN_NEWLINE
        "    va_end(args);" BSGEN_NEWLINE
        "    return _return;" BSGEN_NEWLINE, 
        function->string_format);

    return string;
}

static bsgen_String* bsgen_generateStringTrampolineFunction(bsgen_Library* library, bsgen_String* string, bsgen_Function* function, const char* table_name) {
    bsgen_Function* original = bsgen_fetchUnit(&library->functions, function->generated_from_function_id);
    string = bsgen_appendStringF(string, "    return %s.%s(", table_name, original->name);
    for (int i = 0; i < function->params.count; i++) {
        bsgen_Param* param = bsgen_fetchUnit(&function->params, i);
        string = bsgen_appendStringF(string, "%s, ", param->name);
        if (strcmp(param->name, function->string_format) == 0)
            break;
    }

    string = bsgen_appendStringF(string, "%s_length);" BSGEN_NEWLINE, function->string_format);
    return string;
}

static bsgen_String* bsgen_generateTrampoline(bsgen_String* string, bsgen_Library* library, const char* file_name, const char* table_name) {
   /**
    Typedefs
    */
    for (int i = 0; i < library->functions.count; i++) {
        bsgen_Function* function = bsgen_fetchUnit(&library->functions, i);
        string = bsgen_appendStringF(string, "typedef %s(__stdcall* PFN_%s)(", function->return_value, function->name);

        for (int j = 0; j < function->params.count; j++) {
            bsgen_Param* param = bsgen_fetchUnit(&function->params, j);
            if (param->type)
                string = bsgen_appendStringF(string, "%s %s", param->type, param->name);
            else
                string = bsgen_appendStringF(string, "%s", param->name);

            if (j != (function->params.count - 1))
                string = bsgen_appendString(string, ", ", BSGEN_STRING_LEN(", "));
        }

        string = bsgen_appendString(string, ");" BSGEN_NEWLINE, BSGEN_STRING_LEN(");" BSGEN_NEWLINE));
    }
    string = bsgen_appendString(string, BSGEN_NEWLINE, BSGEN_STRING_LEN(BSGEN_NEWLINE));

   /**
    Table
    */
#define BSGEN_STRUCT_START "struct {" BSGEN_NEWLINE

    string = bsgen_appendString(string, BSGEN_STRUCT_START, BSGEN_STRING_LEN(BSGEN_STRUCT_START));
    for (int i = 0; i < library->functions.count; i++) {
        bsgen_Function* function = bsgen_fetchUnit(&library->functions, i);
        string = bsgen_appendStringF(string, "    PFN_%s %s;" BSGEN_NEWLINE, function->name, function->name);
    }
    string = bsgen_appendStringF(string, "} %s;" BSGEN_NEWLINE BSGEN_NEWLINE, table_name);

   /**
    Declarations
    */
    for (int i = 0; i < library->functions.count; i++) {
        bsgen_Function* function = bsgen_fetchUnit(&library->functions, i);
        string = bsgen_appendStringF(string, "%s %s(", function->return_value, function->name);
        string = bsgen_generateTrampolineFunctionParameters(string, function);
        string = bsgen_appendString(string, BSGEN_END_OF_PARAMETERS, BSGEN_STRING_LEN(BSGEN_END_OF_PARAMETERS));

        switch (function->variadic) {
            case 0: string = bsgen_generateTrampolineFunctionBody(string, function, table_name); break;
            case 1: string = bsgen_generateOriginalVariadicTrampolineFunction(library, string, function, table_name); break;
            //case 1: string = bsgen_generateStringTrampolineFunction(library, string, function, table_name); break;
            case 'N': string = bsgen_generateStringTrampolineFunction(library, string, function, table_name); break;
            case 'F': string = bsgen_generateFormatTrampolineFunction(library, string, function); break;
            case 'V': string = bsgen_generateVariadicFormatTrampolineFunction(library, string, function); break;
        }

        string = bsgen_appendString(string, BSGEN_END_OF_FUNCTION, BSGEN_STRING_LEN(BSGEN_END_OF_FUNCTION));
    }

    printf("%s" BSGEN_NEWLINE, string->value);

    bsgen_saveFile(file_name, string->value, string->len);

    return string;
}

static bsgen_String* bsgen_indentLicense(bsgen_String* license) {
    int license_newline_count = 0;
    for (int i = 0; i < license->len; i++) {
        if (license->value[i] == '\n')
            license_newline_count++;
    }

    int indented_len = license->len + license_newline_count * 2 + 2;
    bsgen_String* license_indented = bsgen_stringAlloc(NULL, indented_len);
    license_indented->value[license_indented->len++] = ' ';
    license_indented->value[license_indented->len++] = ' ';

    int j = license_indented->len;
    for (int i = 0; i < license->len; i++) {
        license_indented->value[j++] = license->value[i];
        if (license->value[i] == '\n') {
            license_indented->value[j++] = ' ';
            license_indented->value[j++] = ' ';
        }
    }

    license_indented->len = j;
    return license_indented;
}

int main(int argc, const char* argv[]) {
    bsgen_String* license = bsgen_loadFile("LICENSE");
    bsgen_String* license_indented = bsgen_indentLicense(license);

    bsgen_Library basilisk_core = bsgen_readLibrary("xml/basilisk-core.xml");

    bsgen_String* string = NULL;

    string = bsgen_string(string, "", 0);
    string = bsgen_appendLicense(string, license_indented);
    string = bsgen_generateHeader(string, &basilisk_core, "basilisk.h", "BASILISK_H", "BSAPI");

    string = bsgen_string(string, "", 0);
    string = bsgen_appendLicense(string, license_indented);
    string = bsgen_appendStringF(string, "#include \"./basilisk.h\"" BSGEN_NEWLINE BSGEN_NEWLINE);
    string = bsgen_generateTrampoline(string, &basilisk_core, "bs_validation.c", "_bs_functions");

    free(string);

	return 0;
}