
 /**
  MIT License
  
  Copyright (c) 2026 hexryro <hexryro@gmail.com>
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.
  */ 

 /**
  This file was generated by basilisk-gen.

  It is not recommended to make changes to this file as it will be lost if
  the code is regenerated.
  */

#ifndef BS_INTERNAL_H
#define BS_INTERNAL_H

#include <vulkan.h>

typedef struct bs_Procs bs_Procs;

#define BS_FOREACH_PROC(X) \
        X(PFN_vkCmdInsertDebugUtilsLabelEXT, vkCmdInsertDebugUtilsLabelEXT) \
        X(PFN_vkCmdBeginDebugUtilsLabelEXT, vkCmdBeginDebugUtilsLabelEXT) \
        X(PFN_vkCmdEndDebugUtilsLabelEXT, vkCmdEndDebugUtilsLabelEXT) \
        X(PFN_vkCmdBeginRenderingKHR, vkCmdBeginRenderingKHR) \
        X(PFN_vkCmdEndRenderingKHR, vkCmdEndRenderingKHR) \
        X(PFN_vkCmdTraceRaysKHR, vkCmdTraceRaysKHR) \
        X(PFN_vkGetAccelerationStructureBuildSizesKHR, vkGetAccelerationStructureBuildSizesKHR) \
        X(PFN_vkCreateAccelerationStructureKHR, vkCreateAccelerationStructureKHR) \
        X(PFN_vkCmdBuildAccelerationStructuresKHR, vkCmdBuildAccelerationStructuresKHR) \
        X(PFN_vkGetAccelerationStructureDeviceAddressKHR, vkGetAccelerationStructureDeviceAddressKHR) \
        X(PFN_vkGetRayTracingShaderGroupHandlesKHR, vkGetRayTracingShaderGroupHandlesKHR) \
        X(PFN_vkDestroyAccelerationStructureKHR, vkDestroyAccelerationStructureKHR) \
        X(PFN_vkCreateRayTracingPipelinesKHR, vkCreateRayTracingPipelinesKHR)

#define BS_STRUCT_GEN(TYPE, FUNC, ...) \
    TYPE FUNC;

struct bs_Procs {
    BS_FOREACH_PROC(BS_STRUCT_GEN);
};

#endif